#!/bin/bash

if test "$#" -lt 3; then
    echo "USAGE: HOST PORT USER [DBNAME] [-c | --create]"
    exit 1
fi

HOST="$1"
PORT="$2"
USER="$3"
DBNAME="gamesdb" || "$4"
CREATE="$5"
echo -n Password: 
read -s PASSWORD
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if test -z $DBNAME; then
  DBNAME="gamesdb"
fi
echo "Using database $DBNAME"

if (test $CREATE = "-c" || test $CREATE = '--create'); then
    STMT_DB="dbname=postgres hostaddr=$HOST port=$PORT user=$USER password=$PASSWORD"
    psql "$STMT_DB" -c "DROP DATABASE $DBNAME;"
    psql "$STMT_DB" -c "CREATE DATABASE $DBNAME;"
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CONFIG="dbname=$DBNAME hostaddr=$HOST port=$PORT user=$USER password=$PASSWORD"

for file in ${DIR}/schema.sql
do
  echo "$file"
  psql "$CONFIG" -f "$file"
done

for script in ${DIR}/seed.sql; do
    echo $script
    psql "$CONFIG" -f $script;
done
